CREATE TABLE overseas_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    report_number VARCHAR(50) NOT NULL COMMENT '报告编号',
    report_number_en VARCHAR(50) NOT NULL COMMENT 'Report Number',
    product_name VARCHAR(255) COMMENT '产品名称',
    product_name_en VARCHAR(255) COMMENT 'Product Name',
    registration_number VARCHAR(100) COMMENT '注册证编号',
    registration_number_en VARCHAR(100) COMMENT 'Registration Number',
    manufacturing_country VARCHAR(100) COMMENT '产地',
    manufacturing_country_en VARCHAR(100) COMMENT 'Manufacturing Country',
    management_category VARCHAR(50) COMMENT '管理类别',
    management_category_en VARCHAR(50) COMMENT 'Management Category',
    product_category VARCHAR(100) COMMENT '产品类别',
    product_category_en VARCHAR(100) COMMENT 'Product Category',
    batch_number VARCHAR(100) COMMENT '产品批号',
    batch_number_en VARCHAR(100) COMMENT 'Batch Number',
    product_number VARCHAR(100) COMMENT '产品编号',
    product_number_en VARCHAR(100) COMMENT 'Product Number',
    udi VARCHAR(100) COMMENT 'UDI',
    udi_en VARCHAR(100) COMMENT 'UDI',
    manufacturing_date DATE COMMENT '生产日期',
    manufacturing_date_en DATE COMMENT 'Manufacturing Date',
    expiration_date DATE COMMENT '有效期',
    expiration_date_en DATE COMMENT 'Expiration Date',
    event_date DATE COMMENT '事件发生日期',
    event_date_en DATE COMMENT 'Event Date',
    discovery_date DATE COMMENT '发现或悉知日期',
    discovery_date_en DATE COMMENT 'Discovery Date',
    injury_type VARCHAR(50) COMMENT '伤害类型',
    injury_type_en VARCHAR(50) COMMENT 'Injury Type',
    injury_description TEXT COMMENT '伤害表现',
    injury_description_en TEXT COMMENT 'Injury Description',
    patient_name VARCHAR(100) COMMENT '姓名',
    patient_name_en VARCHAR(100) COMMENT 'Patient Name',
    birth_date DATE COMMENT '出生日期',
    birth_date_en DATE COMMENT 'Birth Date',
    age_unit VARCHAR(20) COMMENT '年龄单位',
    age_unit_en VARCHAR(20) COMMENT 'Age Unit',
    age_number VARCHAR(20) COMMENT '年龄数字',
    age_number_en VARCHAR(20) COMMENT 'Age Number',
    gender VARCHAR(10) COMMENT '性别',
    gender_en VARCHAR(10) COMMENT 'Gender',
    medical_record_number VARCHAR(100) COMMENT '病历号',
    medical_record_number_en VARCHAR(100) COMMENT 'Medical Record Number',
    medical_history TEXT COMMENT '既往病史',
    medical_history_en TEXT COMMENT 'Medical History',
    malfunction_description TEXT COMMENT '故障表现',
    malfunction_description_en TEXT COMMENT 'Malfunction Description',
    intended_use TEXT COMMENT '预期治疗疾病或作用',
    intended_use_en TEXT COMMENT 'Intended Use',
    device_use_date DATE COMMENT '器械使用日期',
    device_use_date_en DATE COMMENT 'Device Use Date',
    use_location VARCHAR(100) COMMENT '使用场所',
    use_location_en VARCHAR(100) COMMENT 'Use Location',
    facility_name TEXT COMMENT '场所名称',
    facility_name_en TEXT COMMENT 'Facility Name',
    usage_process TEXT COMMENT '使用过程',
    usage_process_en TEXT COMMENT 'Usage Process',
    combined_medication TEXT COMMENT '合并用药器械情况说明',
    combined_medication_en TEXT COMMENT 'Combined Medication',
    investigation_conducted VARCHAR(10) COMMENT '是否展开调查',
    investigation_conducted_en VARCHAR(10) COMMENT 'Investigation Conducted',
    investigation_details TEXT COMMENT '调查情况',
    investigation_details_en TEXT COMMENT 'Investigation Details',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_report_number (report_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='海外报告表'; 